# Spring DataSource Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/audree_db
    username: root
    password: your_password

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update

  # Web Configuration
  web:
    resources:
      add-mappings: true
  mvc:
    throw-exception-if-no-handler-found: true
# Swagger Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Server Configuration
server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: always

# Logging Configuration
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

